export enum TransferStatus {
  CREATED = 'CREATED',
  VALIDATING = 'VALIDATING',
  PENDING_MFA = 'PENDING_MFA',
  PENDING_FRAUD_REVIEW = 'PENDING_FRAUD_REVIEW',
  APPROVED = 'APPROVED',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  REJECTED = 'REJECTED',
  REVERSED = 'REVERSED',
}

export enum IdempotencyStatus {
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum FraudDecision {
  ALLOW = 'ALLOW',
  REQUIRE_STEP_UP_MFA = 'REQUIRE_STEP_UP_MFA',
  HOLD_FOR_REVIEW = 'HOLD_FOR_REVIEW',
  REJECT = 'REJECT',
}
